### PR TITLE
Update dracula.fish

### PR DESCRIPTION
**Pull request by timorunge**
> If you're fixing a UI issue, make sure you take two screenshots. One that shows the actual bug and another that shows how you fixed it.

### CODE REVIEW

**Comment by m-dango** [comment]
Ah, I wasn't sure what these did at first but now I see!

I think it may be a good idea to invert foreground and selection for progress for the highlighted effect.

Also, I think yellow may be a better fit for the description. What do you think?

**Comment by timorunge** [comment]
> I think it may be a good idea to invert foreground and selection for progress for the highlighted effect.

I've something similar in my (custom) neomutt configuration for the progress bar which is `color progress default color238` what's similar to the selection over here. 

I've inverted it to see the result and it's looking good as well but kind of obtrusive.

> Also, I think yellow may be a better fit for the description. What do you think?

Personally I'd go for the "comment" color. For me it's additional information which don't needs a highlight. 


I think it's a general decision where to drive the fish theme through. Some minimal dracula color like theme or something with more contrast.

**Comment by m-dango** [comment]
Yeah you're right the comment color is fitting for the description.

I have noticed in the syntax highlighting for vim when you get to the end of a search it uses orange, maybe we could use that for the color_progress background, I think it looks good!

**Comment by timorunge** [comment]
I'd stay with `--background=$selection`. :)

**Pull request closed without merging**
